### Option 1 tout dans le fichier configuration
# Switch ON/OFF pour machine Linux (Wake-on-LAN + SSH shutdown)
switch:
  - platform: wake_on_lan
    mac: "XX:XX:XX:XX:XX:XX"  # Adresse MAC de votre machine Linux
    name: "Linux Server"
    host: "192.168.1.XXX"     # Adresse IP de votre machine Linux
    broadcast_address: "192.168.1.255"  # Adresse broadcast de votre réseau
    turn_off:
      service: shell_command.shutdown_linux

# Commande shell pour éteindre la machine Linux via SSH
shell_command:
  shutdown_linux: "ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 USERNAME@IP_LINUX 'sudo shutdown -h now'"

### Option 2 fichiers séparés
# Inclusion des fichiers de configuration
switch: !include switch.yaml
shell_command: !include shell_command.yaml
