alias: Chambre - Éclairage automatique présence
description: Allume/éteint la lumière de la chambre selon la présence détectée par LD2410
triggers:
  - entity_id:
      - binary_sensor.esp_chambre_presence
    trigger: state
    from: null
    to: null
    for:
      hours: 0
      minutes: 0
      seconds: 3
    id: chambre
conditions:
  - condition: not
    conditions:
      - condition: state
        entity_id: input_text.jour_nuit
        state: nuit
  - condition: template
    value_template: >
      {% set scene_dodo = states.scene.hue_chambre_5_dodo %} {% if
      scene_dodo.last_changed %}
        {% set minutes_ago = (now() - scene_dodo.last_changed).total_seconds() / 60 %}
        {{ minutes_ago > 10 }}
      {% else %}
        true
      {% endif %}
    alias: Scène dodo pas activée dans les 10 dernières minutes
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.esp_chambre_presence
            state: "on"
          - condition: numeric_state
            entity_id: sensor.esp_chambre_lux
            below: 1
        sequence:
          - action: script.eclairage_intelligent_multi_pieces
            data:
              piece: "{{ trigger.id }}"
      - conditions:
          - condition: state
            entity_id: binary_sensor.esp_chambre_presence
            state: "off"
        sequence:
          - target:
              entity_id: light.hue_chambre
            action: light.turn_off
            data: {}
mode: single
