alias: Chambre - Éclairage automatique présence
description: Allume/éteint la lumière de la chambre selon la présence détectée par LD2410
triggers:
  - entity_id:
      - binary_sensor.esp_chambre_presence
    trigger: state
    from: null
    to: null
    for:
      hours: 0
      minutes: 0
      seconds: 3
    id: chambre
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.esp_chambre_presence
            state: "on"
          - condition: numeric_state
            entity_id: sensor.esp_chambre_lux
            below: 1
        sequence:
          - action: script.eclairage_intelligent_multi_pieces
            data:
              piece: "{{ trigger.id }}"
      - conditions:
          - condition: state
            entity_id: binary_sensor.esp_chambre_presence
            state: "off"
        sequence:
          - target:
              entity_id: light.hue_chambre
            action: light.turn_off
            data: {}
mode: single
