alias: Salle de Bain - Éclairage automatique présence
description: >-
  Allume/éteint la lumière de la salle de bain selon la présence détectée par
  LD2410
triggers:
  - entity_id: binary_sensor.esp_sdb_presence
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.esp_sdb_presence
            state: "on"
          - condition: state
            entity_id: sensor.etat_canabang_et_device_tracker
            state: home
          - condition: numeric_state
            entity_id: sensor.esp_sdb_lux
            below: 1
          - condition: state
            entity_id: light.hue_sdb
            state: "off"
          - condition: template
            value_template: |
              {{ states('cover.volsdb') not in ['opening', 'closing'] }}
          - condition: not
            conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: switch.prismal
                    state: "on"
                  - condition: numeric_state
                    entity_id: sensor.prismal_power
                    above: 5
        sequence:
          - choose:
              - conditions:
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: input_text.jour_nuit
                        state: nuit
                      - condition: template
                        value_template: >
                          {% set dernier_changement =
                          states('input_datetime.dernier_changement_jour_nuit')
                          %} {% if dernier_changement not in ['unknown',
                          'unavailable'] %}
                            {% set changement_datetime = as_timestamp(dernier_changement) %}
                            {% set current_timestamp = now().timestamp() %}
                            {% set diff_seconds = current_timestamp - changement_datetime %}
                            {{ diff_seconds < 1200 and states('input_text.jour_nuit') == 'jour' }}
                          {% else %}
                            false
                          {% endif %}
                sequence:
                  - target:
                      entity_id: scene.hue_sdb_1_veilleuse
                    action: scene.turn_on
                    data: {}
              - conditions:
                  - condition: state
                    entity_id: input_text.jour_nuit
                    state: jour
                sequence:
                  - choose:
                      - conditions:
                          - condition: state
                            entity_id: sun.sun
                            state: above_horizon
                        sequence:
                          - target:
                              entity_id: scene.hue_sdb_2_stimulation
                            action: scene.turn_on
                            data: {}
                      - conditions:
                          - condition: state
                            entity_id: sun.sun
                            state: below_horizon
                        sequence:
                          - target:
                              entity_id: scene.hue_sdb_3_attenue
                            action: scene.turn_on
                            data: {}
      - conditions:
          - condition: state
            entity_id: binary_sensor.esp_sdb_presence
            state: "off"
        sequence:
          - target:
              entity_id: light.hue_sdb
            action: light.turn_off
            data: {}
mode: single
