alias: Éclairage SDB - Présence/Absence
description: Gère l'éclairage de la salle de bain selon la détection de présence
triggers:
  - entity_id: binary_sensor.esp_sdb_presence
    from: "off"
    to: "on"
    id: presence
    trigger: state
  - entity_id: binary_sensor.esp_sdb_presence
    from: "on"
    to: "off"
    id: absence
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: presence
        sequence:
          - data:
              piece: sdb
              source: presence
            action: script.gerer_eclairage
      - conditions:
          - condition: trigger
            id: absence
        sequence:
          - data:
              piece: sdb
              source: absence
            action: script.gerer_eclairage
mode: single
