alias: Pet Feeder - Recalcul automatique des portions
description: Recalcule et applique les portions quand le poids unitaire change
triggers:
  - entity_id:
      - number.pet_feeder_portion_weight
      - input_number.pet_feeder_target_daily_weight
    trigger: state
    for:
      seconds: 3
conditions:
  - condition: template
    value_template: |
      {{ trigger.from_state is not none and 
         trigger.to_state is not none and
         trigger.to_state.state not in ['unknown', 'unavailable'] and
         trigger.to_state.state | float(0) > 0 }}
actions:
  - delay:
      seconds: 2
  - variables:
      portions_matin: "{{ states('sensor.portions_calculees_matin') | int(8) }}"
      portions_midi: "{{ states('sensor.portions_calculees_midi') | int(9) }}"
      portions_soir: "{{ states('sensor.portions_calculees_soir') | int(12) }}"
      poids_portion: "{{ trigger.to_state.state | float(3) }}"
  - action: mqtt.publish
    data:
      topic: zigbee2mqtt02/Pet feeder/set
      payload: |
        {
          "schedule": [
            {"days": "everyday", "hour": 8, "minute": 0, "size": {{ portions_matin }}},
            {"days": "everyday", "hour": 14, "minute": 0, "size": {{ portions_midi }}},
            {"days": "everyday", "hour": 20, "minute": 0, "size": {{ portions_soir }}}
          ]
        }
  - action: system_log.write
    data:
      message: >
        Pet Feeder: Portions recalculées pour {{ poids_portion }}g/portion.
        Nouvelle répartition: Matin={{ portions_matin }}p, Midi={{ portions_midi
        }}p, Soir={{ portions_soir }}p. Total théorique: {{ (portions_matin +
        portions_midi + portions_soir) * poids_portion }}g/jour
      level: info
mode: single



alias: Mise à jour du poids total distribué (cumulatif)
description: >-
  Met à jour le compteur cumulatif et le stock estimé quand un repas est
  distribué
triggers:
  - entity_id:
      - sensor.poids_reel_distribue_aujourd_hui
    trigger: state
conditions:
  - condition: template
    value_template: |
      {{ trigger.from_state is not none and trigger.to_state is not none and
         trigger.to_state.state not in ['unknown', 'unavailable'] and
         trigger.from_state.state not in ['unknown', 'unavailable'] and
         trigger.to_state.state | float(0) > 0 }}
actions:
  - variables:
      poids_distribue: |
        {{ trigger.to_state.state | float(0) }}
      stock_actuel: |
        {{ states('input_number.pet_feeder_stock_estime') | float(0) }}
      nouveau_stock: |
        {{ [stock_actuel - poids_distribue, 0] | max | round(1) }}
      total_cumulatif_actuel: |
        {{ states('input_number.pet_feeder_total_distributed') | float(0) }}
      nouveau_total_cumulatif: |
        {{ (total_cumulatif_actuel + poids_distribue) | round(1) }}
  - data:
      entity_id: input_number.pet_feeder_stock_estime
      value: "{{ nouveau_stock }}"
    action: input_number.set_value
  - data:
      entity_id: input_number.pet_feeder_total_distributed
      value: "{{ nouveau_total_cumulatif }}"
    action: input_number.set_value
  - action: system_log.write
    data:
      message: >
        Pet Feeder: {{ poids_distribue }}g distribués.  Stock: {{ stock_actuel
        }}g → {{ nouveau_stock }}g.  Total cumulatif: {{ total_cumulatif_actuel
        }}g → {{ nouveau_total_cumulatif }}g
      level: info
mode: single

alias: Pet Feeder - Mise à jour compteur consommation
description: Ajoute le poids du dernier repas au compteur quotidien
triggers:
  - entity_id:
      - sensor.poids_reel_distribue_aujourd_hui
    trigger: state
    from: null
    to: null
conditions:
  - condition: template
    value_template: |
      {{ trigger.to_state.state | float(0) > 0 and 
         trigger.from_state.state != trigger.to_state.state }}
actions:
  - target:
      entity_id: input_number.pet_feeder_daily_consumption_counter
    data:
      value: >
        {% set current =
        states('input_number.pet_feeder_daily_consumption_counter') | float(0)
        %} {% set new_meal = trigger.to_state.state | float(0) %} {{ current +
        new_meal }}
    action: input_number.set_value

alias: Pet Feeder - Détection rechargement et reset
description: Détecte le rechargement (passage de <300g à >950g) et remet le compteur à zéro
triggers:
  - entity_id:
      - input_number.pet_feeder_stock_estime
    trigger: state
    from: null
    to: null
conditions:
  - condition: template
    value_template: |
      {{ trigger.from_state.state | float(0) < 300 and 
         trigger.to_state.state | float(0) > 950 }}
actions:
  - target:
      entity_id: input_number.pet_feeder_daily_consumption_counter
    data:
      value: 0
    action: input_number.set_value
  - target:
      entity_id: input_boolean.pet_feeder_stock_was_low
    action: input_boolean.turn_off
    data: {}

alias: Pet Feeder - Suivi stock bas
description: Marque quand le stock passe en dessous de 300g
triggers:
  - entity_id: input_number.pet_feeder_stock_estime
    below: 300
    trigger: numeric_state
actions:
  - target:
      entity_id: input_boolean.pet_feeder_stock_was_low
    action: input_boolean.turn_on
    data: {}
